name: 'ar_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'ar_dbt_project'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ar_dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
